// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 0fc17f08e66aab0696b0eae7b14ecb4d176420feba7eec977e03cb4a1e9ee851

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "planingo-theme";

export const themeNames: ThemeName[] = ["planingo-theme"];

export type KcEnvName = "ENABLE_THEME_TOGGLE";

export const kcEnvNames: KcEnvName[] = ["ENABLE_THEME_TOGGLE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ENABLE_THEME_TOGGLE: "true"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
